### PR TITLE
Restore admin mode settings on rotation.

### PR DESCRIPTION
**Pull request by Shubhamr837**
onSaveInstanceState and onRestoreInstanceState are used to restore state of settings.
should fix https://github.com/odk-x/tool-suite-X/issues/216

### CODE REVIEW

**Comment by wbrunette** [comment]
runtests

**Comment by wbrunette** [comment]
@Shubhamr837, I have a question/concern, if you enter admin mode how do you get out of it? With the Services app often running continually because Survey and Tables access Services background tasks for database and webserver operations, my concern is the saved state will live until the application goes away which might not happen until a device reboot or exiting all ODK-X apps. This would be non-obvious to a user how to logout of admin.

I completely agree that the screen rotation was broken, but I don't want to create another issue as well.

Thoughts?

@linl33 @jbeorse  feel free to chime in

**Comment by Shubhamr837** [comment]
@wbrunette I understand this concern . We can implement another option in the settings menu to get back to normal settings mode .

 The survey and tables application starts the activity from a new intent . So I don't think this problem will occur as initially the admin mode is set to false for a new intent  .

I also tested this on my device ( android 10) . Survey and services both ran different instances of the same activity and running one in admin mode didn't had any impact on the other .

**Comment by wbrunette** [comment]
@Shubhamr837 Thanks for checking into my question. I feel better that coming in from another intent would not have the settings persist.

The two use cases off the top my head for the admin mode is an admin developing/debugging, or setting up properties on the device. Once they are done they would hand the device back to a user and not want them to be able to change the settings. Therefore, I think it would be good to add the option in the settings menu to complete this issue. 

If you wouldn't mind adding the option to exit admin mode that would be awesome? If you don't have time create an issue so we won't forget.

**Comment by Shubhamr837** [comment]
Thanks , I have enough time .
 I will update this pull requests within 24 hours

**Comment by Shubhamr837** [comment]
Hi @wbrunette ! I have added an option to exit admin mode .
screenshot

I have added the spanish translations using google translate .
Please review .
Thanks

**Comment by linl33** [comment]
runtests

**Review by linl33 — APPROVED** [review]

**Review by wbrunette — APPROVED** [review]

**Pull request merged**
