### PR TITLE
fixed#213-show dialogbox

### PR DESCRIPTION
**Pull request by sanyud24**
closes https://github.com/odk-x/tool-suite-X/issues/213
demo: https://drive.google.com/file/d/1dKjK1Uy_8JSzcCQv9YhP3XCIoHmoxLRx/view?usp=sharing

### CODE REVIEW

**Comment by wbrunette** [comment]
runtests

**Comment by wbrunette** [comment]
@maprehensive please review to make sure it works like you envision.

**Comment by wbrunette** [comment]
@maprehensive please review to make sure it works like you envision.

**Comment by wbrunette** [comment]
@maprehensive please review to make sure it works like you envision so it will count as completed contribution.

**Review by maprehensive — APPROVED** [review]
Hi @sanyud24 and @wbrunette 

I've looked at the implementation in the emulator and it looks good to me. 

The inclusion of the cancel button while the sync prep message shows is good. 

The button style needs an update, but that needs some further inputs from the UI Uplift project so I would pass this now.

cheers, Ben

**Comment by sanyud24** [comment]
Sure!! @maprehensive

**Pull request merged**
