### PR TITLE
Fixing typos in README.md file

### PR DESCRIPTION
**Pull request by julian55455**
Fixing typos in README.md file

cc @elmps2018  @wbrunette

### CODE REVIEW

**Review by elmps2018 — APPROVED** [review]

**Comment by elmps2018** [comment]
@julian55455 thanks for these changes! @wbrunette can you check what the bot said before I merge?

**Comment by wbrunette** [comment]
runtests

**Comment by julian55455** [comment]
@wbrunette are the build failures raising from any of my changes?

**Comment by wbrunette** [comment]
runtests

**Pull request merged**
